server:
  port: 8888
  servlet:
    context-path: /${spring.application.name}/

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketplace
    username: user
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: false
  application:
    name: marketplace