version: '3.8'
services:
  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - '${DOCKER_HOST_PORT}:${CONTAINER_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase_marketplace
    command: --url="jdbc:postgresql://${DB_HOST}:${CONTAINER_PORT}/${LIQUIBASE_DB}?currentSchema=${LIQUIBASE_SCHEMA}" --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=${CHANGELOG_FILE}  --logLevel=info update
    volumes:
      - ./main/resources/db:/liquibase/main/resources/db
    # Ожидаем пока БД не станет доступна
    depends_on:
      - db
    extra_hosts:
      - "${DB_HOST}:host-gateway"

volumes:
  db:
    driver: local